# Generated by Django 5.2.4 on 2025-08-09 01:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=100)),
                ('post_detail', models.TextField(max_length=1000)),
                ('created_by', models.CharField(max_length=100)),
                ('post_time', models.TimeField(default=django.utils.timezone.now)),
                ('post_date', models.DateField(default=django.utils.timezone.now)),
                ('slug_link', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
